GitHubUsersRepository.Web/ViewModels/GitHubRepositoryViewModel.cs
namespace GitHubUsersRepository.ViewModels
{
    public class GitHubRepositoryViewModel
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public int StargazersCount { get; set; }
    }
}

GitHubUsersRepository.Web/ViewModels/GitHubUserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GitHubUsersRepository.ViewModels
{
    public class GitHubUserViewModel
    {
        [Required(ErrorMessage = "UserName Required")]
        public string Login { get; set; }
        public int Id { get; set; }
        public string AvatarUrl { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        public int PublicRepos { get; set; }
        public int PublicGists { get; set; }
        public int Followers { get; set; }
        public int Following { get; set; }
        public string Location { get; set; }
        public bool Success { get; set; }

        public List<GitHubRepositoryViewModel> Repositories { get; set; }
    }
}

GitHubUsersRepository.Web/Controllers/GitHubUserController.cs
using GitHubUsersRepository.Services.Abstract;
using GitHubUsersRepository.ViewModels;
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GitHubUsersRepository.Controllers
{
    public class GitHubUserController : Controller
    {

        private readonly IGitHubUserService _gitHubUserService;

        public GitHubUserController(IGitHubUserService gitHubUserService)
        {
            _gitHubUserService = gitHubUserService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Search(GitHubUserViewModel gitHubUserViewModel)
        {
            if (ModelState.IsValid)
            {
                var url = ConfigurationManager.AppSettings["GitHubUserURL"];
                var value = await _gitHubUserService.GetGitHubUser(url, gitHubUserViewModel.Login);
                return View("Index", value);
            }

            return View("Index", null);
        }
        
    }
}

GitHubUsersRepository.Web/Views/GitHubUser/Index.cshtml
@model GitHubUsersRepository.ViewModels.GitHubUserViewModel
@{ 
    ViewBag.Title = "Search GitHub User";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

@using (Html.BeginForm("Search", "GitHubUser", FormMethod.Post, new { @class = "user-form" }))
{
    @Html.ValidationMessageFor(m => m.Login, "", new { @class = "text-danger" })
    <br />
    @Html.TextBoxFor(x => x.Login, null, new { @placeholder = "Search by GitHub username" })
    <button type="submit">Search <span class="glyphicon glyphicon-search"></span></button>}
    @if (Model != null)
    {
        if (Model.Success)
        {
            <main id="main">

                <div class="card">
                    <div>
                        <img src="@Model.AvatarUrl" alt="@Model.Login" class="avatar">
                    </div>
                    <div class="user-info">
                        <h2>@(!string.IsNullOrEmpty(Model.Name) ? $"{Model.Name} ({Model.Login})" : @Model.Login)</h2>
                        @Model.Bio
                        <h6><span class="glyphicon glyphicon-map-marker"></span> Location: @(Model.Location ?? "Not provided")</h6>
                        <ul class="follow">
                            <li>@Model.Followers <strong>Followers</strong></li>
                            <li>@Model.Following <strong>Following</strong></li>
                            <li>@Model.PublicRepos <strong>Repos</strong></li>
                        </ul>
                        <hr />
                        <div id="repos">
                            @if (Model.Repositories != null && Model.Repositories.Count > 0)
                            {
                                foreach (var repository in Model.Repositories)
                                {
                                    <a class="repo" target="_blank" href="@repository.Url">
                                        <span class="stars">(@repository.StargazersCount <span class="glyphicon glyphicon-star"></span>)</span><label class="title"> @repository.Name</label>
                                        <label class="description">@repository.Description</label>
                                    </a>
                                }
                            }
                            else
                            {
                                <h4>This user has no repository.</h4>
                            }
                        </div>
                    </div>
                </div>
            </main>
        } 
        else
        {
            <h2>User "@Model.Login" not found.</h2>
        }
}

GitHubUsersRepository.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>    
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>